name: Netlify Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Netlify
        env:
          NETLIFY_MCP_PROXY: "https://netlify-mcp.netlify.app/proxy/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..G_pWljOmVNvKyYfH.gdHY9tXOeL9gC0uq_0-umtOLKnER6dUbY9Mcm1Y_FlRbanKfIbqI-vAdT7xmjBJ5oOV97T2sCimDiqfErCo4LjmRHZegxhcfG5751fRANuhvIMcjb2rqri1qgrlTTi8vGxY5xfQZJUk1NF7Z3jW_D5kjrpCAWNCr8raZsSWwYVqaT8Ntl1fNpvS5Mbt5RWdSv2afMVLeSJB61ZaAOAf0bboiHqgm9n9oP1jrMQk_RzayA6NfNwETrEImfXkiW9FMdS8Ek4wBHvODwjAZ48tfLrFFuGgrdybj5uZur35hqQo5nZ0xUoH8oC6re4MZhTAJRUiDcyvT8nsoqBpTKQh7e2CV0M4yfMHQKFub1w0kQs8TH3K9EyLRV0vgEmGMqTZY6gdZCfSG.MbNG_BXLYAUiRhiY6beLvw"
        run: npx -y @netlify/mcp@latest --site-id "72599492-3fcb-4604-bdd8-a5ef8324f2f0" --proxy-path "$NETLIFY_MCP_PROXY"
